config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,    presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { maximum: 105 },
                       format: { with: VALID_EMAIL_REGEX }
                       
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def edit
  end
  
  def create
    @article = Article.new(article_params)
    
    #Temporary hardcoded user
    @article.user = User.first
    
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully edited"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @article.destroy
    flash[:success] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private
  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  
  end
  
  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "Welcome to Alpha Blog #{ @user.username }"
      redirect_to articles_path
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      flash[:success] = "Your account was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    size = 70
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{ gravatar_id }?s=#{ size }"
    image_tag(gravatar_url, alt: user.username)
  end
end

app/views/articles/_article.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Created by</th>
    <th>Created</th>
    <th>Last updated</th>
  </tr>
  
  <% obj.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      
      <!-- Temporary fix because db has articles with nill user -->
      <td><%= article.user.username if article.user %></td>
      
      <td><%= time_ago_in_words(article.created_at) %> ago</td>
      <td><%= time_ago_in_words(article.updated_at) %> ago</td>
      <td><%= link_to "Edit", edit_article_path(article) %></td>
      <td><%= link_to "Show", article_path(article) %></td>
      <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h3>The following errors prevented the aricle from getting created</h3>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back to aricles listing", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>

<p>
  <%= link_to "Create new article", new_article_path %>
</p>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>
  Title: <%= @article.title %>
</p>

<% if @article.user %>
  <ul>
    <li>Created by:</li>
    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
    <li><%= link_to @article.user.username, user_path(@article.user) %></li>
    <li><%= pluralize(@article.user.articles.count, "article") %></li>
  </ul>
<% end %>

<p>
  Description: <%= @article.description %>
</p>

<%= link_to "Edit this article", edit_article_path(@article) %>
<br/>

<%= link_to "Back to aricles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    
    <%= yield %>
    
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Blog homepage</h1>

<%= link_to 'About', about_path %>

<%= link_to 'Articles listing', articles_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h3>The following errors prevented the aricle from getting created</h3>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %>
    <br/>
    <%= f.text_field :username, placeholder: "Enter username" %>
  </p>
  <p>
    <%= f.label :email %>
    <br/>
    <%= f.email_field :email, placeholder: "Enter email address" %>
  </p>
  <p>
    <%= f.label :password %>
    <br/>
    <%= f.password_field :password, placeholder: "Enter password" %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>All Alpha Bloggers</h1>

<% @users.each do |user| %>
  <ul>
    <li><%= link_to gravatar_for(user), user_path(user) %></li>
    <li><%= link_to user.username, user_path(user) %></li>
    <% if user.articles.count != 0 %>
      <li><%= pluralize(user.articles.count, "article") %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username %>'s profile</h1>

<%= gravatar_for(@user) %>

<h4><%= @user.username %>'s articles</h4>
<%= render 'articles/article', obj: @user.articles %>